version: '2'

services:
  api: &API
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment: &WEB_ENV
      RAILS_ENV: development
    links:
      - postgres
    logging:
      options:
        max-file: '5'
        max-size: 1m
    networks:
      - default

  postgres:
    image: postgres:9.6.1
    logging:
      options:
        max-file: '5'
        max-size: 1m

  pgweb:
    image: sosedoff/pgweb
    command: [
      /usr/bin/pgweb, --bind=0.0.0.0, --ssl=disable, --db=quiz_api_development,
      --host=postgres, --user=postgres, --pass=quiz_api_postgres_password
    ]
    links:
      - postgres
