version: '2'

services:
  web: &WEB
    build:
      context: .
      dockerfile: Dockerfile
    environment: &WEB_ENV
      RAILS_ENV: development
    links:
      - postgres
    logging:
      options:
        max-file: '5'
        max-size: 1m
    networks:
      - default

  postgres:
    image: postgres:11
    logging:
      options:
        max-file: '5'
        max-size: 1m

  pgweb:
    image: sosedoff/pgweb
    command: [
      /usr/bin/pgweb, --bind=0.0.0.0, --ssl=disable, --db=meal_maid_development,
      --host=postgres, --user=postgres, --pass=meal_maid_postgres_password
    ]
    links:
      - postgres
