services:
  - postgres:latest

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - cp config/database.yml.gitlab config/database.yml

test:
  stage: test
  script:
  - apt-get update -qy
  - bundle install --path /cache
  - bundle exec rails db:create db:migrate RAILS_ENV=test
  - bundle exec rspec
